name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  workflow:
    name: Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install NPM dependencies
        run: npm install

      - name: Run Linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true

      - name: Run Unit Testing
        run: npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
